// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class QuestionsBank
{
    public int QuestionId { get; set; }

    public string Type { get; set; }

    public string Content { get; set; }

    public int? Points { get; set; }

    public int? CrsId { get; set; }

    public virtual ICollection<Answer> Answers { get; set; } = new List<Answer>();

    public virtual Course Crs { get; set; }

    public virtual ICollection<Exam> ExamNos { get; set; } = new List<Exam>();
}