// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Student
{
    public int StdId { get; set; }

    public string Fname { get; set; }

    public string Lname { get; set; }

    public int? Age { get; set; }

    public string Email { get; set; }

    public string ProfilPicture { get; set; }

    public DateTime? JoinDate { get; set; }

    public string Phone { get; set; }

    public int? UserId { get; set; }

    public int? DeptId { get; set; }

    public virtual Department Dept { get; set; }

    public virtual ICollection<StudentCourse> StudentCourses { get; set; } = new List<StudentCourse>();

    public virtual User User { get; set; }
}