// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class StudentAnswerV2
{
    public int StdAnsId { get; set; }

    public string StudentAns { get; set; }
}