// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.Models;

public partial class Topic
{
    public int CrsId { get; set; }

    public string Topic1 { get; set; }

    public virtual Course Crs { get; set; }
}