// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.StoredProcModel;

public partial class Answer
{
    public int AnsId { get; set; }

    public int QuestionId { get; set; }

    public string Content { get; set; }

    public bool IsCorrect { get; set; }

    public virtual QuestionsBank Question { get; set; }
}