// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.StoredProcModel
{
    public partial class selectStudentAnswersResult
    {
        public int Std_Ans_Id { get; set; }
        public string student_choices { get; set; }
    }
}
