// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.StoredProcModel
{
    public partial class selectUsersResult
    {
        public int user_id { get; set; }
        public string username { get; set; }
        public string user_password { get; set; }
        public int type { get; set; }
        public string state { get; set; }
        public DateTime? Last_Login { get; set; }
    }
}
