// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.StoredProcModel
{
    public partial class selectDepartmentsResult
    {
        public int dept_id { get; set; }
        public string dept_name { get; set; }
        public string description { get; set; }
        public int? mgr_id { get; set; }
    }
}
