// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace Examination_System.StoredProcModel
{
    public partial class selectStudentExamAnswersResult
    {
        public int? Ques_ID { get; set; }
        public int? stdid { get; set; }
        public int? examid { get; set; }
        public int? Std_Ans_Id { get; set; }
        public int? grades { get; set; }
    }
}
