// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.StoredProcModel;

public partial class StudentExamAnswer
{
    public int? QuesId { get; set; }

    public int? Stdid { get; set; }

    public int? Examid { get; set; }

    public int? StdAnsId { get; set; }

    public int? Grades { get; set; }
}