// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Examination_System.StoredProcModel;

public partial class StudentCourse
{
    public int CrsId { get; set; }

    public int StdId { get; set; }

    public int? CrsGrade { get; set; }

    public virtual Course Crs { get; set; }

    public virtual Student Std { get; set; }
}